module.exports = {
  apps: [
    {
      name: "donassistec-backend",
      script: "./backend/dist/index.js",
      cwd: "/home/DonAssistec",
      instances: 1,
      exec_mode: "fork",
      env: {
        NODE_ENV: "production",
        PORT: 3001,
        DB_HOST: "localhost",
        DB_PORT: 3307,
        DB_NAME: "donassistec_db",
        DB_USER: "donassistec_user",
        DB_PASSWORD: "donassistec_password",
        CORS_ORIGIN: "http://localhost:8200",
        // JWT_SECRET: Set via environment variable - NEVER hardcode!
        JWT_EXPIRES_IN: "7d",
      },
      error_file: "./logs/backend-error.log",
      out_file: "./logs/backend-out.log",
      log_file: "./logs/backend-combined.log",
      time: true,
      autorestart: true,
      watch: false,
      max_memory_restart: "500M",
    },
    {
      name: "donassistec-frontend",
      script: "npm",
      args: "run dev",
      cwd: "/home/DonAssistec",
      instances: 1,
      exec_mode: "fork",
      env: {
        NODE_ENV: "development",
        PORT: 8200,
        // VITE_API_URL removido - o código detecta automaticamente
      },
      error_file: "./logs/frontend-error.log",
      out_file: "./logs/frontend-out.log",
      log_file: "./logs/frontend-combined.log",
      time: true,
      autorestart: true,
      watch: false,
      max_memory_restart: "300M",
    },
  ],
};
