CREATE TABLE IF NOT EXISTS retailer_price_tables (
  id INT AUTO_INCREMENT PRIMARY KEY,
  slug VARCHAR(120) NOT NULL UNIQUE,
  title VARCHAR(255) NOT NULL,
  effective_date VARCHAR(50) NULL,
  visible_to_retailers BOOLEAN NOT NULL DEFAULT TRUE,
  raw_text LONGTEXT NOT NULL,
  parsed_data JSON NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
